### ISSUE TITLE
Error: Deployment manifest contains 'stemcells' section, but it can only be used in cloud-config

### ISSUE THREAD

**Issue by kumarganesh2814** [cppforlife/zookeeper-release#9]
Hi,

I am getting below error trying this Example on Vsphere. 

While running command as below:

```
# bosh -e dbaas -d zookeeper deploy manifests/zookeeper.yml
```

Error: 

```
Task 7 | 16:24:18 | Preparing deployment: Preparing deployment (00:00:00)
                   L Error: Deployment manifest contains 'stemcells' section, but it can only be used in cloud-config.
Task 7 | 16:24:19 | Error: Deployment manifest contains 'stemcells' section, but it can only be used in cloud-config.

Task 7 Started  Tue Mar  6 16:24:18 UTC 2018
Task 7 Finished Tue Mar  6 16:24:19 UTC 2018
Task 7 Duration 00:00:01
Task 7 error

Updating deployment:
  Expected task '7' to succeed but state is 'error'

Exit code 1
```

Please advise 

Best Regards
Ganesh Kumar

**Comment by kumarganesh2814** [comment]
Was able to Fix Issue after uploading proper cloud-config 

Commnad to be used

```
bosh -e dbaas update-cloud-config cloud.yml

```

Sample cloud.yml

```
azs:
- name: z1
  cloud_properties:
    datacenters:
    - clusters: [AppOps_KM_Cluster: {}] #Chage this as per your ESXI Host
- name: z2
  cloud_properties:
    datacenters:
    - clusters: [z2: {}]

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 1024
    disk: 3240
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 30_240

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: default
  type: manual
  subnets:
  - range: 10.112.76.0/22 #Chage this as per your ESXI Host
    gateway: 10.112.79.253#Chage this as per your ESXI Host
    az: z1
    dns: [10.112.64.1,10.112.64.2] #Chage this as per your ESXI Host
    cloud_properties:
      name: VM Network
compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: large
  network: default
```

Best Regards
Ganesh Kumar
